### ISSUE TITLE
Add thumbnail in the image component of the create discount form

### ISSUE THREAD

**Issue by MiroBenicio** [tiki/tiki-shopify-web#38]
### Reason

Needs to Show an thumbnail of the image selected by the user in the Drop zone Component

### Description

Needs to add a thumbnail component inside the drop zone component to show the selected image

This thumbnail its not in the 1.0 milestone because an Typescript Global Type Error in the Window Object used to pick up the image.

### Success Criteria

- [ ] A thumbnail with the selected image working

**Comment by ricardobrg** [comment]
outdated
